name: Run drawio test
on: workflow_call

permissions:
  contents: read

env:
  DRAW_IO_VERSION: "26.0.9"
jobs:
  verify-images:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache draw.io installer
        id: cache-drawio
        uses: actions/cache@v4
        with:
          path: drawio-installer.exe
          key: drawio-${{ env.DRAW_IO_VERSION }}
          restore-keys: |
            drawio-

      - name: Download installer if not cached
        if: steps.cache-drawio.outputs.cache-hit != 'true'
        run: |
          curl -L -o drawio-installer.exe https://github.com/jgraph/drawio-desktop/releases/download/v${{ env.DRAW_IO_VERSION }}/draw.io-${{ env.DRAW_IO_VERSION }}-windows-installer.exe

      - name: Install Software
        run: |
          Start-Process -FilePath "drawio-installer.exe" -ArgumentList "/S" -Wait
        shell: powershell

      - name: Run drawio
        run: |
          Start-Process -FilePath "C:\Program Files\draw.io\draw.io.exe" -ArgumentList "-xf","png","-o","security-info-chatbot.png","security-info-chatbot.drawio" -Wait
        shell: powershell
